import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import stylePlugin from 'esbuild-style-plugin';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';


import fs from 'node:fs';
import path from 'node:path';

const renamePlugin = {
	name: 'rename-css',
	setup(build) {
		build.onEnd(() => {
			const cssFile = path.join(build.initialOptions.outdir || '.', 'main.css');
			const target = path.join(build.initialOptions.outdir || '.', 'styles.css');
			if (fs.existsSync(cssFile)) {
				fs.renameSync(cssFile, target);
			}
		});
	},
};


const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	outdir: '.',
	plugins: [
		stylePlugin({
			postcss: {
				plugins: [tailwindcss, autoprefixer],
			},
			extract: true,           // 启用提取为单独 CSS 文件
			cssBundle: 'styles.css', // 指定输出文件名（会在 outdir 下生成 ./styles.css）
		}),
		renamePlugin
	],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	// outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
